#!/usr/bin/env ruby
require 'rubygems'
require 'bundler'
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('./Gemfile', __dir__)
Bundler.require :default
require_relative './lib/petli/hud'
Petli::HUD.new.run
